import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    paddingTop: 30,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
  headerSection: {
    height: 100,
    flexDirection: "row",
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 15,
    marginRight: 15,
  },
  searchSection: {
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
  },
  serviceSection: {
    height: 100,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 15,
    marginRight: 15,
  },
  cardSection: {
    height: 200,
    backgroundColor: "#D6F6FF",
    alignItems: "center",
    justifyContent: "center",
    margin: 15,
    borderRadius: 20,
    flexDirection: "row",
    shadowOpacity: 0.05,
  },
  statusSection: {
    height: 200,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 15,
    marginRight: 15,
  },
  headerText: { fontSize: 15, color: "#000", fontWeight: "400" },
  headerTextSection: {
    flex: 7,
    alignItems: "flex-start",
    justifyContent: "center",
  },
  headerUsername: {
    fontSize: 25,
    fontWeight: "bold",
    color: "#009DC7",
    marginTop: 5,
  },
  headerUserSection: {
    flex: 3,
    alignItems: "flex-end",
    justifyContent: "flex-end",
    flexDirection: "row",
  },
  headerUserImage: { width: 50, height: 50, borderRadius: 20, marginTop: 5 },
  serviceHeaderText: {
    flex: 1,
    fontSize: 18,
    fontWeight: "600",
    color: "#000",
    alignContent: "center",
  },
  serviceButtonContainer: {
    flex: 8,
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
  },
  serviceButton: {
    width: 60,
    height: 60,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    margin: 10,
    shadowOpacity: 0.1,
  },
  serviceHeaderTextContainer: {
    flex: 2,
    alignItems: "flex-start",
    justifyContent: "center",
    flexDirection: "row",
    marginBottom: 10,
  },
  buttonIcon: { margin: 10 },
  searchIconSection: {
    flex: 1.5,
    alignItems: "center",
    justifyContent: "center",
  },
  searchInputSection: { flex: 7, justifyContent: "center" },
  filterIcon: { flex: 1.5, alignItems: "center", justifyContent: "center" },
  sugarRateContainer: {
    flex: 4,
    width: "40%",
    height: "80%",
    backgroundColor: "#6BCB77",
    borderRadius: 20,
    elevation: 10,
    margin: 15,
    alignItems: "center",
    justifyContent: "center",
  },
  sugarRateContainerWarning: {
    flex: 4,
    width: "40%",
    height: "80%",
    backgroundColor: "#F24C4C",
    borderRadius: 20,
    elevation: 10,
    margin: 15,
    alignItems: "center",
    justifyContent: "center",
  },
  sugarButtonContainer: {
    flex: 6,
    width: "80%",
    height: "80%",
    alignItems: "center",
  },
  sugarButton: {
    backgroundColor: "#009DC7",
    borderRadius: 10,
    flex: 5,
    margin: 5,
    width: "80%",
    height: "40%",
    alignItems: "center",
    justifyContent: "center",
    elevation: 10,
    flexDirection: "row",
  },
  sugarButtonText: {
    fontSize: 12,
    color: "white",
    fontWeight: "600",
    marginLeft: 5,
  },
  BMISection: {
    flex: 4,
    backgroundColor: "#F5E1E9",
    alignItems: "center",
    justifyContent: "center",
    height: "80%",
    width: "40%",
    borderRadius: 20,
    elevation: 10,
    margin: 10,
    shadowOpacity: 0.05,
  },
  CommentSection: {
    flex: 6,
    backgroundColor: "#DCEDF9",
    alignItems: "center",
    justifyContent: "center",
    height: "80%",
    width: "40%",
    borderRadius: 20,
    elevation: 10,
    margin: 10,
    shadowOpacity: 0.05,
  },
  statusHeaderTextContainer: {
    flex: 2,
    alignItems: "flex-start",
    justifyContent: "center",
    flexDirection: "row",
  },
  statusText: {
    flex: 1,
    fontSize: 18,
    fontWeight: "600",
    color: "#000",
    alignContent: "center",
  },
  statusContainer: {
    flex: 9,
    flexDirection: "row",
    justifyContent: "space-around",
  },
  BMIIcon: {
    flex: 4,
    alignItems: "flex-start",
    justifyContent: "center",
    marginTop: 10,
    width: "70%",
  },
  BMIText: {
    flex: 6,
    fontSize: 25,
    color: "black",
    fontWeight: "600",
  },
  BMITextContainer: {},
  commentIcon: {
    flex: 2,
    height: "100%",
    alignItems: "flex-start",
    justifyContent: "center",
    marginTop: 10,
    width: "70%",
    elevation: 10,
  },
  commentText: {
    fontSize: 15,
    color: "black",
    fontWeight: "600",
    textAlign: "center",
  },
  commentTextContainer: {
    flex: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  centeredView: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  modalView: {
    backgroundColor: "white",
    width: "80%",
    height: 200,
    borderRadius: 20,
    padding: 35,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  modalText: { fontSize: 20, fontWeight: "bold", color: "#9AA0B8" },
  sugarateInput: {
    height: "40%",
    borderColor: "#9AA0B8",
    borderWidth: 1,
    width: "80%",
    marginTop: 10,
    borderRadius: 10,
    width: "50%",
    alignContent: "center",
    justifyContent: "center",
    textAlign: "center",
  },
  modalButtonContainer: {
    width: "80%",
    flexDirection: "row",
    marginTop: 15,
    justifyContent: "space-around",
    alignItems: "center",
  },
  modalButtonCancel: {
    width: 100,
    height: 40,
    borderRadius: 10,
    backgroundColor: "#9AA0B8",
    alignItems: "center",
    justifyContent: "center",
  },
  modalButtonConfirm: {
    width: 100,
    height: 40,
    borderRadius: 10,
    backgroundColor: "#009DC7",
    marginLeft: 30,
    alignItems: "center",
    justifyContent: "center",
  },
  modalButtonTextCancel: { fontSize: 15, color: "white", fontWeight: "bold" },
  modalButtonTextConfirm: { fontSize: 15, color: "white", fontWeight: "bold" },
  modalInputContainer: {
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    marginTop: 10,
    height: "40%",
  },
  measureInput: {
    height: "80%",
    borderColor: "#9AA0B8",
    borderWidth: 1,
    marginTop: 10,
    borderRadius: 10,
    width: "40%",
    alignContent: "center",
    justifyContent: "center",
    textAlign: "center",
  },
});
